// This file is generated by kconfig_compiler from kasconfig.kcfg.
// All changes you do to this file will be lost.

#include "kasconfig.h"

#include <kstaticdeleter.h>

KASConfig *KASConfig::mSelf = 0;
static KStaticDeleter<KASConfig> staticDeleter;

KASConfig *KASConfig::self()
{
  if ( !mSelf ) {
    staticDeleter.setObject( mSelf, new KASConfig() );
    mSelf->readConfig();
  }

  return mSelf;
}

KASConfig::KASConfig(  )
  : KConfigSkeleton( "kasconfig" )
{
  mSelf = this;
  setCurrentGroup( "kaudioscrobbler" );

  KConfigSkeleton::ItemString  *itemusername;
  itemusername = new KConfigSkeleton::ItemString( currentGroup(), "username", mUsername );
  addItem( itemusername );
  KConfigSkeleton::ItemString  *itempassword;
  itempassword = new KConfigSkeleton::ItemString( currentGroup(), "password", mPassword );
  addItem( itempassword );
  KConfigSkeleton::ItemInt  *itemcachesaveinterval;
  itemcachesaveinterval = new KConfigSkeleton::ItemInt( currentGroup(), "cachesaveinterval", mCachesaveinterval, 5 );
  addItem( itemcachesaveinterval );
}

KASConfig::~KASConfig()
{
  if ( mSelf == this )
    staticDeleter.setObject( mSelf, 0, false );
}

