// This file is generated by kconfig_compiler from kasconfig.kcfg.
// All changes you do to this file will be lost.
#ifndef KASCONFIG_H
#define KASCONFIG_H

#include <kconfigskeleton.h>

class KASConfig : public KConfigSkeleton
{
  public:

    static KASConfig *self();
    ~KASConfig();

    /**
      Get AudioScrobbler username
    */
    static
    QString username()
    {
      return self()->mUsername;
    }

    /**
      Get AudioScrobbler password
    */
    static
    QString password()
    {
      return self()->mPassword;
    }

    /**
      Get Cache Save Interval
    */
    static
    int cachesaveinterval()
    {
      return self()->mCachesaveinterval;
    }

    static
    void writeConfig()
    {
      static_cast<KConfigSkeleton*>(self())->writeConfig();
    }
  protected:
    KASConfig();
    static KASConfig *mSelf;


    // kaudioscrobbler
    QString mUsername;
    QString mPassword;
    int mCachesaveinterval;

  private:
};

#endif
